
---
version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=America/Sao_Paulo
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - ./config/jackett:/config
      #- <path to blackhole>:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=America/Sao_Paulo
      - UMASK_SET=002 #optional
    volumes:
      - ./config/sonarr:/config
      - /media/hdd/tv:/tv
      - /media/hdd/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

 jellyfin:
   image: linuxserver/jellyfin
   container_name: jellyfin
   environment:
     - PUID=1002
     - PGID=1002
     - TZ=America/Sao_Paulo
     - UMASK_SET=002 #optional
   volumes:
     - ./config/jellyfin:/config
     - /media/hdd/tv:/data/tvshows
     - /media/hdd/movies:/data/movies
     #- /path for transcoding:/transcode #optional
     #- /opt/vc/lib:/opt/vc/lib #optional
   ports:
     - 8096:8096
     - 8920:8920 #optional
     - 7359:7359/udp  
     - 1900:1900  
   devices:
     - /dev/dri:/dev/dri #optional
     #- /dev/vchiq:/dev/vchiq #optional
   restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=America/Sao_Paulo
      - UMASK_SET=002
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - /media/hdd/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
